### PR TITLE
Stillshot features

### PR DESCRIPTION
**Pull request by mowcixo**
Having tested @tomiu fork with stillshot features, I think is a good non-intrusive fork for taking pictures, and it takes all good features from the original repository by @afollestad like retry, etc...

It was a little outdated, so I rebased it, fixed problems and updated doc.

I think is a good idea to merge it in the original repository.

### CODE REVIEW

**Comment by sugarmanz** [comment]
Quick question. Would this implementation allow for dynamic switching between still shot and video mode? Or would the activity need to be restarted to switch?

**Comment by mowcixo** [comment]
@sugarmanz The current implementation would need an activity restart to switch. As I wrote in the README:

```java
new MaterialCamera(this)
    /** all the previous methods can be called, but video ones would be ignored */
    .stillShot(); // launches the Camera in stillshot mode
    .start(CAMERA_RQ);
```

**Comment by sugarmanz** [comment]
@mowcixo Cool. Thanks. PS. I really hope this is approved.

**Comment by tkrupicka** [comment]
I think adding some sort of mode toggle is the last thing this would need to be a drop-in replacement for a default camera. That might be something worth looking in to. Nice work @mowcixo.

**Comment by mowcixo** [comment]
@tkrupicka @sugarmanz 

Thinking about how an embedded cam activity works, I think launching the activity with video/picture preset is good because you would always know what to expect at **onActivityResult**. But I agree that would be a nice feature.

**Comment by mowcixo** [comment]
Aside of the improvements from @tomiu and @jakubbroz I've posted in this PR, those days I've made this changes:

* The intent returned in **setResult** was returning video/mp4 mime for pictures too, so now when it is a picture, it returns image, it returns image/jpeg.
* When the camera was started in stillshot mode, the RECORD_AUDIO permission was requested too, so now when it is stillshot mode, it only ask for CAMERA permission, but later if it's started in classic video mode, it ask for it.

**Comment by sugarmanz** [comment]
Hey @mowcixo, we've been trying to help out and test the compatibility of this feature to make sure its safe to put in. So far, we've tested the `mowcixo:master` (commit 635589d) sample application on a samsung galaxy 6 edge+ and nexus 6p both running Marshmallow 6.0.1. But with both devices, the application reports that camera2 is not supported when trying to start the camera for either still-shot or video. Both devices work fine with the `afollestad:master` sample app. Any ideas?

**Comment by mowcixo** [comment]
Hey @sugarmanz, it is hard to tell, because I don't have any of these devices to test... but there is no difference between my fork and `afollestad:master` with the `CameraUtil#hasCamera2` function, so... can I suggest a test battery so we can figure out where the problem is?

- One difference are the lines of hardware in the manifest, can you try to remove these lines and try again?: 

`<uses-feature android:name="android.hardware.camera" />`
`<uses-feature android:name="android.hardware.camera.autofocus" />`

- Then, in MaterialCamera.java, line `272`, can you put a breakpoint and check the values of `mForceCamera1`, `CameraUtil.hasCamera2(mContext)`, and then the value of `cls` variable?

By the other hand... anyone knows if there are any config to create a Virtual Device with Camera2 with the AVD?

**Comment by sugarmanz** [comment]
@mowcixo I believe camera2 is available with any device  api 21 (lollipop) and above. So, I would think that any Virtual Device that has Lollipop or higher should use Camera2. With the AVD, one can specify a Webcam to use for the Virtual Device. 

Regarding the actual code: upon initial investigation, I didn't see many changes near that area of code (as you have pointed out). But I will try the changes you have suggested tomorrow and let you know if anything changes.

Thanks for the help.

**Comment by mowcixo** [comment]
@sugarmanz In fact yes, camera2 API is available with any device api >=21, but in the majority of phones it is not supported by hardware level, as a member of Google say at this link: https://code.google.com/p/android/issues/detail?id=82219#c8 (yes, a little outdated)

For example, my Meizu MX5 is Lollipop api 22, but the result for `characteristics.get(CameraCharacteristics.INFO_SUPPORTED_HARDWARE_LEVEL)` is 2 (`INFO_SUPPORTED_HARDWARE_LEVEL_LEGACY`), so the function `CameraUtil.hasCamera2(mContext)` returns `false`.

Also, I've found this app wich test Camera2 features: https://play.google.com/store/apps/details?id=pl.vipek.camera2_compatibility_test

**Comment by mowcixo** [comment]
In this article https://spectrastudy.com/camera2-api-on-mwc-2015-devices/#more-34 they explain that in LEGACY level, Camera2 creates a wrapper over legacy camera.

**Comment by tylerkrupicka** [comment]
@mowcixo: @sugarmanz and I have been testing the still-shot features on our range of devices and have found some more bugs. We'll submit a pull request when we have a tested patch soon, but I thought I'd let you know that we're still working on it.

**Comment by tylerkrupicka** [comment]
Hey @mowcixo. @sugarmanz and I have a patch ready in my fork that should fix a lot of stuff, but at the last minute we found an error for the Galaxy S5. We're looking in to that now, but hopefully it's simple.

**Comment by tylerkrupicka** [comment]
https://github.com/mowcixo/material-camera/pull/2

**Comment by sugarmanz** [comment]
## Changelog

We've submitted a number of bug fixes that resolve all of the issues we were seeing with the stillshot branch. @tylerkrupicka and I tested these changes on a range of devices, and while it doesn't cover everything, we feel that all of the non edge-cases have been resolved. We're including some details of the fixes for reference.

#### Camera2 Bug

@sugarmanz fixed a bug with the Camera2 stillshot implementation that caused a "not supported" error on all of our devices. This issue was caused by the use of an uninitialized mPreviewSize.

#### Flash

The flash implementation caused a lot of errors with all of our devices. The branch was improperly checking which flash modes are available, as well as making assumptions based on whether or not the phone supported flash at all. Additionally, the flash icon would appear even if it wasn't supported -- which was very misleading.

To remedy this, we wrote more robust flash mode checks that should work on all devices. These checks include some weird ways of saying the flash is unavailable, as well as properly hiding the flash icon when flash is unavailable. We also made sure that the flash logic no longer is used in video mode, as the logic for controlling that using "torch" mode is entirely different. This should ensure that the flash feature doesn't cause any errors. 

#### Permissions Errors

@sugarmanz fixed a bug where the video camera would start if camera permissions were previously granted w/o audio permissions (most likely from using the stillshot mode). Audio permissions were requested and applied to an already open camera -- causing a crash. Requiring audio for the video mode should no longer have any issues.

#### Samsung-specific flash issues

Samsung devices using Camera2 do not handle flash well: we were encountering freezing issues and errors returning images while in stillshot mode and using flash. After doing research on how this is usually handled, we found that it is common to force the Camera1 API for stillshot on Samsung devices. We verified this with some online resources, as well as the popular cwac stillshot camrera library (which is very stable). Making this changed remedied all of the flash-specific Samsung errors. 

#### Galaxy S3 Fixes

Material-camera (current master and the stillshot fork) did not work at all in rear-facing camera mode on our test Galaxy S3. After a lot of debugging and research @sugarmanz was able to fix it in both video and stillshot mode, which required a small amount of (unfortunate) device-specific conditionals. If other Samsung phones on Camera1 are found to have these issues at a later date we can expand the conditional to include those models.

#### Bitmap preview OutOfMemory fix
We discovered an Out of Memory Error caused by large images not being properly downsized for phones with higher resolution cameras. The problem being, that with phones that take very large images (S5 has 16 MP camera), the preview image would ask for too much memory. The fix was to continually increase the `inSampleSize` until the bitmap was small enough to display. Though this was found with the S5, it is probable that this problem would occur in many devices that take really large images -- which should no longer be an issue.

### Testing

Here's the final list of working devices now that bugs are resolved.

| Device              | Manufacturer | OS  | Video | Stillshot | Flash | Front & Back |
| ------------------- |:------------:|:---:|:-----:|:---------:|:-----:|:------------:|
| Nexus 6p            | Huewei       |6.0.1|   ✓  |      ✓    |   ✓   |       ✓     |
| Nexus 5             | LG           |6.0.1|   ✓  |      ✓    |   ✓   |       ✓     |
| Droid Razr Maxx     | Motorolla    |4.4.2|   ✓  |      ✓    |   ✓   |       ✓     |
| Galaxy S6           | Samsung      |6.0.1|   ✓  |      ✓    |   ✓   |       ✓     |
| Galaxy S5           | Samsung      |5.0.0|   ✓  |      ✓    |   ✓   |       ✓     |
| Galaxy S3 (SCH-I525)| Samsung      |4.4.2|   ✓  |      ✓    |   ✓   |       ✓     |

### Going Forward

We finally feel pretty confident that these new features won't cause any obvious errors, and shouldn't interfere with the existing video functionality or make it less stable. We're hoping @afollestad can take a look and hopefully get these features added soon.

**Comment by tylerkrupicka** [comment]
We've fully tested stillshot on the HTC One M8 and Nexus 7. Working with no changes necessary. The nexus 7 preview is a little blurry but it's the same as video.

| Device              | Manufacturer | OS  | Video | Stillshot | Flash | Front & Back |
| ------------------- |:------------:|:---:|:-----:|:---------:|:-----:|:------------:|
| One M8              | HTC             |6.0.0|   ✓  |      ✓    |   ✓   |       ✓     |
| Nexus 7              | ASUS           |6.0.1|   ✓  |      ✓    |   ✓   |       ✓     |

**Comment by afollestad** [comment]
Thanks for the major contributions everyone!

I'll do some addition testing when I get the chance.

**Comment by mowcixo** [comment]
@afollestad thank you for the amazing lib!! :)

**Comment by afollestad** [comment]
Unfortunately there's quite a lot of new bugs related to stillshot:

https://github.com/afollestad/material-camera/issues?q=is%3Aopen+is%3Aissue+label%3Astillshot

**Comment by afollestad** [comment]
Also, `ImageUtil.getRotatedBitmap()` is very inefficient, it appears to be causing an `OutOfMemoryError` on various low-RAM devices.

**Comment by afollestad** [comment]
https://github.com/afollestad/material-camera/releases/tag/0.4.1

**Comment by tylerkrupicka** [comment]
@afollestad: @sugarmanz and I can hopefully resolve some of those. We've been using stillshot pretty extensively in a testing app and we've found some issues with the auto submit logic on stillshot as well. It seems to ignore telling it to auto submit and show the review screen anyways. We're back in school at the moment so time is tight but we'll take a look when we can. We've found a couple friends who have a Galaxy S4 and S5 so we can (hopefully) look in to some of the bugs (especially OOM errors) related to those phones as well.

**Comment by Allenliubowen** [comment]
Hello,Nexus 6P Android 7.11 take picture with flash mode on .Picture no effect.

**Pull request merged**
